@startuml

title __TESTSCROLLINGACTIVITY's Class Diagram__\n

  namespace android.arch.core {
    class android.arch.core.R {
    }
  }
  

  namespace android.arch.lifecycle {
    class android.arch.lifecycle.R {
    }
  }
  

  namespace android.arch.lifecycle {
    namespace livedata {
      class android.arch.lifecycle.livedata.R {
      }
    }
  }
  

  namespace android.arch.lifecycle {
    namespace livedata {
      namespace core {
        class android.arch.lifecycle.livedata.core.R {
        }
      }
    }
  }
  

  namespace android.arch.lifecycle {
    namespace viewmodel {
      class android.arch.lifecycle.viewmodel.R {
      }
    }
  }
  

  namespace android.support.asynclayoutinflater {
    class android.support.asynclayoutinflater.R {
    }
  }
  

  namespace android.support.compat {
    class android.support.compat.R {
    }
  }
  

  namespace android.support.coordinatorlayout {
    class android.support.coordinatorlayout.R {
    }
  }
  

  namespace android.support.coreui {
    class android.support.coreui.R {
    }
  }
  

  namespace android.support.coreutils {
    class android.support.coreutils.R {
    }
  }
  

  namespace android.support.cursoradapter {
    class android.support.cursoradapter.R {
    }
  }
  

  namespace android.support.customview {
    class android.support.customview.R {
    }
  }
  

  namespace android.support.design {
    class android.support.design.R {
    }
  }
  

  namespace android.support.documentfile {
    class android.support.documentfile.R {
    }
  }
  

  namespace android.support.drawerlayout {
    class android.support.drawerlayout.R {
    }
  }
  

  namespace android.support.fragment {
    class android.support.fragment.R {
    }
  }
  

  namespace android.support.graphics.drawable {
    class android.support.graphics.drawable.R {
    }
  }
  

  namespace android.support.interpolator {
    class android.support.interpolator.R {
    }
  }
  

  namespace android.support.loader {
    class android.support.loader.R {
    }
  }
  

  namespace android.support.localbroadcastmanager {
    class android.support.localbroadcastmanager.R {
    }
  }
  

  namespace android.support.print {
    class android.support.print.R {
    }
  }
  

  namespace android.support.slidingpanelayout {
    class android.support.slidingpanelayout.R {
    }
  }
  

  namespace android.support.swiperefreshlayout {
    class android.support.swiperefreshlayout.R {
    }
  }
  

  namespace android.support.transition {
    class android.support.transition.R {
    }
  }
  

  namespace android.support.v7.appcompat {
    class android.support.v7.appcompat.R {
    }
  }
  

  namespace android.support.v7.cardview {
    class android.support.v7.cardview.R {
    }
  }
  

  namespace android.support.v7.recyclerview {
    class android.support.v7.recyclerview.R {
    }
  }
  

  namespace android.support.v7.viewpager {
    class android.support.v7.viewpager.R {
    }
  }
  

  namespace androidx.versionedparcelable {
    class androidx.versionedparcelable.R {
    }
  }
  

  namespace com.t.testscrollingactivity {
    class com.t.testscrollingactivity.BuildConfig {
    }
  }
  

  namespace com.t.testscrollingactivity {
    class com.t.testscrollingactivity.R {
    }
  }
  

  namespace com.t.testscrollingactivity {
    namespace test {
      class com.t.testscrollingactivity.test.BuildConfig {
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
